vich_uploader:
    db_driver: orm

    mappings:
        utilisateur_image:
            uri_prefix: /images/Utilisateurs
            upload_destination: '%kernel.project_dir%/public/images/Utilisateurs'

            inject_on_load   : false
            delete_on_update : true
            delete_on_remove : true