vich_uploader:
    db_driver: orm

    #  mapings:
    #      utilisateur_images:
    #          uri_prefix: /images/utilisateurs
    #          upload_destination: '%kernel.project_dir%/public/images/utilisateurs'

    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
