<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUrdA2Uj\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUrdA2Uj/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUrdA2Uj.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUrdA2Uj\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerUrdA2Uj\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'UrdA2Uj',
    'container.build_id' => 'd87d72db',
    'container.build_time' => 1564999271,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUrdA2Uj');
