<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerX9SLhWQ\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerX9SLhWQ/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerX9SLhWQ.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerX9SLhWQ\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerX9SLhWQ\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'X9SLhWQ',
    'container.build_id' => 'f0090799',
    'container.build_time' => 1567387280,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerX9SLhWQ');
