<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHb0Yjfk\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHb0Yjfk/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHb0Yjfk.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHb0Yjfk\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHb0Yjfk\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Hb0Yjfk',
    'container.build_id' => 'afee5ebb',
    'container.build_time' => 1565099620,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHb0Yjfk');
